FROM sf23/droidaugmentor:latest
RUN apt-get update 
RUN apt-get -y install git wget curl net-tools ssh
WORKDIR /droidaugmentor
RUN rm -rf /droidaugmentor/*
USER root
COPY ./scripts/docker_setup /droidaugmentor/setup
RUN chmod +x /droidaugmentor/setup/ssh_github.sh
RUN /droidaugmentor/setup/ssh_github.sh
COPY ./scripts/docker_setup/docker_run.sh /usr/bin/docker_run.sh
RUN chmod +x /usr/bin/docker_run.sh 
CMD ["docker_run.sh"]
