FROM sf23/droidaugmentor:latest
RUN apt-get update 
RUN apt-get -y install git wget curl net-tools ssh vim
RUN pip install pipenv
WORKDIR /droidaugmentor
#RUN rm -rf /droidaugmentor/*
USER root
COPY ./scripts/docker_setup /droidaugmentor/setup
RUN chmod +x /droidaugmentor/setup/ssh_github.sh
RUN chmod +x /droidaugmentor/setup/install_requirements.sh
COPY ./requirements.txt /droidaugmentor/setup
RUN /droidaugmentor/setup/docker_install_requirements.sh
RUN /droidaugmentor/setup/ssh_github.sh
RUN mv /droidaugmentor/setup/docker_run.sh /usr/bin/docker_run.sh
RUN chmod +x /usr/bin/docker_run.sh 
CMD ["docker_run.sh"]
